name: scanner
description: Runs sonar-scanner
author: Benjamin Nørgaard
inputs:
  caCert: 
    description: MTLS ca cert
    required: true
  clientCert:
    description: MTLS client cert
    required: true
  clientKey:
    description: MTLS client key
    required: true
  host:
    description: Sonarqube host
    required: true
    default: https://sonar.ts.sv
  token:
    description: Sonarqube access token
    required: true
runs:
  using: docker
  image: docker://eu.gcr.io/tradeshift-public/sonarqube-scanner:56b00aed8c8e02bdcb73063ff2c9863c97c7a652
